
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db1
        username: root
        password: anurag

    jpa:
        generate-ddl: true
        show-sql: true
        
        hibernate:
            ddl-auto: create
        properties:
            hibernate: 
